name: packagist_widgets
description: widget library
version: 1.3.6
homepage: https://github.com/flutter-packagist/widgets

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1   # 网络图片加载
  easy_refresh: ^3.4.0           # 下拉刷新，上拉加载
  dio: ^5.7.0                    # 网络请求
  vector_math: ^2.1.0            # vector_math
  packagist_network: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
