name: packagist_widgets
description: widget library
version: 1.4.3
homepage: https://github.com/flutter-packagist/widgets

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1   # 网络图片加载
  easy_refresh: ^3.4.0           # 下拉刷新，上拉加载
  dio: ^5.8.0+1                  # 网络请求
  vector_math: ^2.1.4            # vector_math
  extended_image: ^10.0.1
  packagist_network: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
